name: webapp-test-dev

on:
  push:
    branches:
       - '!main'
       - '**'
  
       

jobs:
  testcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install python
        uses: actions/setup-python@v2 #install python
        with:
          python-version: 3.9
      
      - name: install pckg
        run: |
          pip3 install Flask
          pip3 install flake8
          
      - name: run flake8 test code
        run: flake8 .

  build_webapp:
    runs-on: ubuntu-latest
    needs: [testcode]
    steps:
        - uses: actions/checkout@v1

        - name: install python
          uses: actions/setup-python@v2 #install python
          with:
            python-version: 3.9
       
        - name: install_pckg
          run : |
              pip3 install Flask
                           
        - name: deploy webapp
          run: sudo docker build .